config/routes.rb
Rails.application.routes.draw do

  get 'restaurants/search'
  get 'restaurants/show'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  
  resources :users
  

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destory'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant
    include HTTParty

    default_params key: '56c9098f4d738b1a', language: 'ja-JP', format: 'json'

    format :json

    def self.search term
        base_uri 'http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?'
        get("", query: { name: term } )
    end

    def self.detail id
        base_uri 'http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?#{id}'
        get("", query: { })
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true,
                    length: {minmum: 1, maximum: 15 }
    validates :email, presence: true,
                      format: {with: /\A\S+@\S+\.\S+\z/ }

    has_secure_password validations: false
    validates :password, presence: true,
                         length: { minmum: 8, maximum: 32 },
                         format: { with: /\A[a-zA-Z0-9]+\z/ }

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    add_flash_types :success, :info, :warning, :danger

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def login?

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def search
    @search_term = params[:name]
    @restaurant_results = []

    if @search_term.present?
       @restaurant_results = JSON.parse(Restaurant.search(@search_term).body)
    end
  end

  def show
    @restaurant_info = Restaurant.details(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'   
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
      
    end
  end

  def destory
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  def log_out 
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
     end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapEats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
  <% end %>
  
 

   <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo2.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
            
              <%= link_to restaurants_search_path do %>
                <%= image_tag "icons/search.png"%>
              <% end %>
                
     
            </li>
            
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

  <script>
    $(function(){
      $(".alert").fadeOut(5000);
    });
  </script>

  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
      <h1 class="text-white">Make you Happy </h1>
      <h2 class="text-white">Map_Eats </h2>

        <div class="row">
          <div class="col-md-offset-3 col-md-3">
            <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white'%>
          </div>
          <div class="col-md-3">
            <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white'%>
          </div>
        </div>
    </div>
</div>

app/views/restaurants/search.html.erb
<h1>レストラン検索</h1>

<div>
  <%= form_tag(restaurants_search_path, method: :get) do %>
    <%= search_field_tag :name, nil, placeholder: 'Restaurant Title...' %>
    <%= submit_tag '検索'%>
  <% end %>
</div>

<div>
  <% if @restaurant_results.blank? %>
    <p>[<%= @search_term %>]と一致する情報が見つかりませんでした</p>
  <% else %>
    <p>[<%= @search_term %>]の検索結果</p>
    <table border="1">
      <tr>
        <th>店名</th>
        <th>URL</th>
        <th>営業時間</th>
        <th>住所</th>
        <th>ジャンル</th>
      </tr>
      <% @restaurant_results.each do |restaurant| %>
      <% restaurant[1]["shop"].each do |shop| %>
        <tr>
        <td><%= link_to shop['name'], id: "#{shop["id"]}" %></td>
        <td><%= shop['urls']%></td>
        <td><%= shop['open']%></td>
        <td><%= shop['address']%></td>
        <td><%= shop['genre']%></td>
        </tr>
      <% end %>
      <% end %>
    </table>
  <%end%>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant_info['name'] %></h1>

<p><strong>住所：</strong><%= @restaurant_info['address']%></p>

<p><strong>最寄駅名:</strong><%= @restaurant_info['station_name']%></p>

<p>
     <strong>ジャンル：</strong>
     <% @restaurant_info['genre'].each do |genre| %>
         <% if genre == @restaurant_info['genre'].last %>
             <span><%= genre['name'] %></span>
         <% else %>
             <span><%= genre['name'] %>、</span>
         <% end %>
     <% end %>
</p>

<p><strong>ロゴ：</strong><%= @restaurant_info['logo_image'] %></p>

app/views/users/new.html.erb
<div class="users-new-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-md-offset-4 col-md-4 users-new-container">
            <h1 class="text-center text-while">Sign in</h1>
            <%= form_for @user do |f| %>
              <div class="form-group">
                <%= f.label :name, class: 'text-white' %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-gruop">
                <%= f.label :email, class: 'text-white' %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password, class: 'text-white'%>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation, class: 'text-white'%>
                <%= f.password_field :password_confirmation, class: 'form-control'%>
              </div>
        
              <%= f.submit "登録", class: 'btn-block btn-white' %>
            <% end %>
             <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
          </div>
      </div>
  </div>
</div>